### PR TITLE
Fixed crash on save

### PR DESCRIPTION
**Pull request by kossolax**
Added a try catch while saving file.

 Issue: https://github.com/TheJelle/Spedit/issues/35

### CODE REVIEW

**Comment by JulienKluge** [comment]
i also added this with a dialog. i'm curious when does this happen?

**Comment by kossolax** [comment]
Your implementation did not work. The crash still happens.

**Comment by JulienKluge** [comment]
Then do me a favour, start the editor with the "-safe" argument, produce
the crash and send me the content of the crashlog.

mfg julien

2015-08-17 8:52 GMT+02:00 Steve Zaretti notifications@github.com:

**Comment by kossolax** [comment]
1
Section: SPEDIT MAIN
.NET Version: 4.0.30319.42000
OS: Microsoft Windows NT 6.2.9200.0
64 bit OS: TRUE
64 bit mode: TRUE
Dir: C:\Users\KoSSoLaX\AppData\Roaming\spedit
Working Set: 179336 kb
Installed UI Culture: fr-FR
Current UI Culture: fr-FR
Current Culture: fr-BE

Exception 1
Message:
Le processus ne peut pas accéder au fichier 'C:\Users\KoSSoLaX\hubiC\Coding\SourceMOD\svn\roleplay\roleplay.inc.events.sp', car il est en cours d'utilisation par un autre processus.
Stacktrace:
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   à Spedit.UI.Components.EditorElement.Save(Boolean Force)
   à Spedit.UI.MainWindow.Command_Save()
   à Spedit.UI.MainWindow.MainWindowEvent_KeyDown(Object sender, KeyEventArgs e)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   à System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   à System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   à System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   à System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   à System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
   à System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à Spedit.Program.Main(String[] args)
Source:
mscorlib
HResult Code:
-2147024864
Helplink:
null
Targetsite Name:
WinIOError

**Pull request closed without merging**
